development:
  adapter: postgresql
  database: portfolio_development
  pool: 5
  timeout: 5000



test:
  adapter: postgresql
  database: portfolio_test
  pool: 5
  timeout: 5000



production:
  adapter: postgresql
  database: portfolio_production
  pool: 5
  timeout: 5000
