development:
  adapter: postgresql
  database: portfolio_development
  pool: 5
  timeout: 5000
  host: localhost
  username: postgres
  password: postgres

test:
  adapter: postgresql
  database: portfolio_test
  pool: 5
  timeout: 5000
  host: localhost
  username: postgres
  password: postgres


production:
  adapter: postgresql
  database: portfolio_production
  pool: 5
  timeout: 5000
